project:
  type: website
  output-dir: docs
website:
  title: "Dhruv Patel"
  description: "Dhruv's personal website"
  repo-actions: [edit, issue]
  open-graph: true
  navbar:
    pinned: True
    collapse-below: lg
    left:
      - icon: house
        href: index.qmd
        text: Home
      - icon: newspaper
        href: blog.qmd
        text: Blog
      - icon: megaphone
        href: talks.qmd
        text: Talks
      - icon: file-person
        href: about.qmd
        text: About
      - text: Other
        icon: stack
        menu:
          - text: "Carlson Q&A"
            icon: box-arrow-up-right
            href: other/carlson.qmd
          - text: "Pytorch Book"
            icon: box-arrow-up-right
            href: https://aayushmnit.com/pytorch_book/
    right:
      - icon: github
        href: https://github.com/dhruvldrp9/
      - icon: linkedin
        href: https://www.linkedin.com/in/dhruvp9/
      - icon: medium
        href: https://medium.com/@aayushmnit
      - icon: mastodon
        href: https://sigmoid.social/@aayushmnit
      - icon: twitter
        href: https://twitter.com/aayushmnit
      - icon: envelope
        href: mailto:dhruv.ldrp9@gmail.com
      - icon: rss
        href: blog.xml

format:
  html:
    theme: 
      light: sandstone
      dark: cyborg
    mainfont: Roboto
    css: styles.css
    toc: true



